### PR TITLE
Remove LINQ usage from Enum conversion from/to string

### LINKED ISSUE #226: Unbounded LINQ expansion in AOT scenarios
The use of LINQ in enum parsing and serialization code is resulting in unbounded LINQ generic specialization expansion that results in crashing the NativeAOT compiler.

A full explanation of the issue is [here](https://github.com/dotnet/runtime/issues/102131#issuecomment-2116806850).

The use of LINQ should be removed from the methods to make the use of Kiota and Microsoft.Graph SDK usable in NativeAOT scenarios.

While not a nice or optimal code I tested that the following diff (along with a similar change in Kiota Form serializer) is enough to stop the problem from occurring:
```diff
diff --git a/src/JsonParseNode.cs b/src/JsonParseNode.cs
index f91286e..cbb5229 100644
--- a/src/JsonParseNode.cs
+++ b/src/JsonParseNode.cs
@@ -218,21 +218,23 @@ namespace Microsoft.Kiota.Serialization.Json
 #endif
         {
             var rawValue = _jsonNode.GetString();
-            if(string.IsNullOrEmpty(rawValue)) return null;
+            if (string.IsNullOrEmpty(rawValue)) return null;

             var type = typeof(T);
             rawValue = ToEnumRawName<T>(rawValue!);
-            if(type.GetCustomAttributes<FlagsAttribute>().Any())
+            if (type.GetCustomAttributes<FlagsAttribute>().Any())
             {
-                return (T)(object)rawValue!
-                    .Split(',')
-                    .Select(x => Enum.TryParse<T>(x, true, out var result) ? result : (T?)null)
-                    .Where(x => !x.Equals(null))
-                    .Select(x => (int)(object)x!)
-                    .Sum();
+                string[] valueNames = rawValue!.Split(',');
+                int value = 0;
+                foreach (string valueName in valueNames)
+                {
+                    if (Enum.TryParse<T>(valueName, true, out var result))
+                        value |= (int)(object)result;
+                }
+                return (T)(object)value;
             }
             else
-                return Enum.TryParse<T>(rawValue, true,out var result) ? result : null;
+                return Enum.TryParse<T>(rawValue, true, out var result) ? result : null;
         }

         /// <summary>
diff --git a/src/JsonSerializationWriter.cs b/src/JsonSerializationWriter.cs
index 4674569..ef11aac 100644
--- a/src/JsonSerializationWriter.cs
+++ b/src/JsonSerializationWriter.cs
@@ -278,16 +278,21 @@ namespace Microsoft.Kiota.Serialization.Json
             if(value.HasValue)
             {
                 if(typeof(T).GetCustomAttributes<FlagsAttribute>().Any())
-                    WriteStringValue(null,
+                {
+                    var values =
 #if NET5_0_OR_GREATER
-                        Enum.GetValues<T>()
+                        Enum.GetValues<T>();
 #else
-                        Enum.GetValues(typeof(T))
-                            .Cast<T>()
+                        Enum.GetValues(typeof(T)).Cast<T>();
 #endif
-                            .Where(x => value.Value.HasFlag(x))
-                            .Select(GetEnumName)
-                            .Aggregate((x, y) => $"{x},{y}"));
+                    List<string> valueNames = new List<string>();
+                    foreach (var x in values)
+                    {
+                        if (value.Value.HasFlag(x) && GetEnumName(x) is string valueName)
+                            valueNames.Add(valueName);
+                    }
+                    WriteStringValue(null, string.Join(",", valueNames));
+                }
                 else WriteStringValue(null, GetEnumName(value.Value));
             }
         }
```

The code can be written in more optimal fashion. Hence, why I submit an issue and not a PR.

### PR DESCRIPTION
**Pull request by filipnavara**
This prevents unintended and unbound generic specialization expansion in the NativeAOT compiler.

Fixes #226

### CODE REVIEW

**Comment by filipnavara** [comment]
> Any chance you can add a changelog entry in the repository root

Yes

> ...as well as bump the patch version in the csproj?

Does it make sense to bump it since it is bumped to 1.3.0 which is still unreleased?

**Comment by filipnavara** [comment]
> Does it make sense to bump it since it is bumped to 1.3.0 which is still unreleased?

Ah, nevermind, it's actually on NuGet already.

**Review by andrueastman — APPROVED** [review]

**Comment by am11** [comment]
Great work @filipnavara, as always! 😎 
In case you missed it, it is in 1.3.1 https://github.com/microsoft/kiota-serialization-json-dotnet/releases/tag/v1.3.1. 🚀

**Comment by filipnavara** [comment]
> Great work @filipnavara, as always! 😎
> In case you missed it, it is in 1.3.1 https://github.com/microsoft/kiota-serialization-json-dotnet/releases/tag/v1.3.1. 🚀

Thanks! Already compiling with it. Let's see how far I can push the limits on the next attempt with our app :)

**Pull request merged**
